# Generated by Django 2.1.7 on 2019-04-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dr_email', models.EmailField(max_length=254, unique=True)),
                ('dr_first_name', models.TextField(max_length=25)),
                ('dr_last_name', models.TextField(max_length=25)),
                ('job_id', models.TextField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('parent_email', models.EmailField(max_length=254, unique=True)),
                ('parent_first_name', models.TextField(max_length=25)),
                ('parent_last_name', models.TextField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_body', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('dr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField()),
                ('account_type', models.IntegerField()),
                ('patient_first_name', models.TextField(max_length=300)),
                ('patient_last_name', models.TextField(max_length=300)),
                ('patient_sex', models.IntegerField()),
                ('patient_birth_date', models.DateField()),
                ('time_stamp', models.DateField()),
                ('result', models.DecimalField(decimal_places=3, max_digits=5)),
                ('quiz', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Quiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Result'),
        ),
    ]
