# Generated by Django 2.1.7 on 2019-04-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Choice'),
            preserve_default=False,
        ),
    ]
