# Generated by Django 2.1.7 on 2019-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dr',
            old_name='username',
            new_name='drEmail',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='dr',
            field=models.IntegerField(),
        ),
    ]
