# Generated by Django 2.1.7 on 2019-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0002_auto_20190512_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
