# Generated by Django 2.1.7 on 2019-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0003_auto_20190411_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='parent',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='test',
            name='account_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
