# Generated by Django 2.1.7 on 2019-04-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0004_auto_20190411_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Result',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='test',
            new_name='result',
        ),
    ]
