# Generated by Django 2.1.7 on 2019-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0004_auto_20190516_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
