# Generated by Django 2.1.7 on 2019-04-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0006_result_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dr',
            old_name='drEmail',
            new_name='dr_email',
        ),
        migrations.RenameField(
            model_name='dr',
            old_name='drFirstName',
            new_name='dr_firstName',
        ),
        migrations.RenameField(
            model_name='dr',
            old_name='drLastName',
            new_name='dr_lastName',
        ),
        migrations.RenameField(
            model_name='dr',
            old_name='jobId',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parentEmail',
            new_name='parent_email',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parentFirstName',
            new_name='parent_firstName',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parentLastName',
            new_name='parent_lastName',
        ),
    ]
