# Generated by Django 2.1.7 on 2019-04-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0007_auto_20190420_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dr',
            old_name='dr_firstName',
            new_name='dr_first_name',
        ),
        migrations.RenameField(
            model_name='dr',
            old_name='dr_lastName',
            new_name='dr_last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parent_firstName',
            new_name='parent_first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parent_lastName',
            new_name='parent_last_name',
        ),
    ]
