# Generated by Django 2.1.7 on 2019-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0008_auto_20190420_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
